fix: verifier rewards
Zilliqa/staking-contract pull request #118
Opened 2020-09-09 08:36 UTC by renlulu

2020-09-09 08:43 UTC, ansnunez approved these changes

2020-09-09 08:45 UTC, bb111189 approved these changes

2020-09-10 03:55 UTC, bb111189 requested changes
I still feel we need some buffer before activation of minting. This is to prevent 
- people from front-running while the contract is being setup
- sufficient time for us to setup the contract and enroll ssn

I suggest either of the following
- a transition to activate minting. activateMining(uint128 blocknum) 
- or hard code a delayed activation block number

2020-09-10 03:55 UTC, bb111189 commented on contracts/gzil.scilla
> +  during_block: Uint128
`during block` abit confusing

maybe  
`num_minting_blocks`

2020-09-10 06:30 UTC, renlulu commented on contracts/gzil.scilla
> +  during_block: Uint128
OK!

2020-09-10 06:31 UTC, AmritKumar commented on contracts/ssnlist.scilla
> +        (* Substract from verifier_reward, scilla would help us with underflow exception which is always should not happen *)
```suggestion
        (* Substract from verifier_reward, scilla would help us with underflow exception which should not happen *)
```

2020-09-10 06:48 UTC, AmritKumar reviewed
1. Please update README accordingly. 
2. The name of the field `verifier_reward` is a bit misleading.
3. Temporary field is being used which is not very clean.

2020-09-10 08:16 UTC, bb111189 commented on contracts/gzil.scilla
> +    end_block_amt = builtin badd _creation_block blocknum;
should it be current block number instead of the creation block number?

2020-09-10 10:38 UTC, bb111189 approved these changes

2020-09-10 15:24 UTC, AmritKumar approved these changes

2020-09-10 15:24 UTC, merged