fix: total stake amount
Zilliqa/staking-contract pull request #129
Opened 2020-09-21 07:53 UTC by renlulu

Fixes #127

2020-09-26 22:49 UTC, AmritKumar commented on contracts/ssnlist.scilla
> -      event e
Why change in `ReDelegStakeAmt`? This is not part of findings in 6.1? Can we move it as a separate PR?

2020-09-26 22:50 UTC, AmritKumar requested changes

2020-09-26 22:50 UTC, AmritKumar commented on contracts/ssnlist.scilla
> -      DecreaseTotalStakeAmt withdraw_amount;
Similarly, why change this code? It's not part of 6.1. Can we move it as a separate PR?

2020-09-27 08:10 UTC, AmritKumar commented
The fix for 6.1 looks ok though. That can be merged.

2020-09-27 08:24 UTC, AmritKumar approved these changes

2020-09-28 06:49 UTC, bb111189 approved these changes

2020-09-28 06:58 UTC, merged