audit 6.27
Zilliqa/staking-contract pull request #156
Opened 2020-09-22 17:21 UTC by renlulu

2020-09-24 15:16 UTC, AmritKumar commented on contracts/ssnlist.scilla
> +      e = { _eventname: "CompleteWithdrawal"; ssnaddr: initiator; initiator: withdraw_amt };
```suggestion
      e = { _eventname: "CompleteWithdrawal"; ssnaddr: initiator; amount: withdraw_amt };
```

2020-09-24 15:24 UTC, AmritKumar commented on contracts/ssnlist.scilla
> +    e = { _eventname: "NoDelegateToWithdral"; ssnaddr: initiator };
```suggestion
    e = { _eventname: "NoPendingWithdrawal"; ssnaddr: initiator };
```

2020-09-24 15:26 UTC, AmritKumar commented on contracts/ssnlist.scilla
> +      e = { _eventname: "NoUnboundDelegate"; ssnaddr: initiator };
```suggestion
      e = { _eventname: "NoUnbondedStake"; ssnaddr: initiator };
```

2020-09-24 15:27 UTC, AmritKumar requested changes
Check the comments.

2020-09-24 15:31 UTC, AmritKumar approved these changes

2020-09-25 07:22 UTC, bb111189 approved these changes

2020-09-28 02:41 UTC, merged