feat: new transaction for claiming admin
Zilliqa/staking-contract pull request #193
Opened 2020-10-04 03:36 UTC by renlulu

2020-10-04 12:45 UTC, bb111189 approved these changes

2020-10-05 05:34 UTC, AmritKumar commented on contracts/README.md
> +|`ClaimAdmin()` | `UpdateAdmin(initiator : ByStr20)`|
```suggestion
|`ClaimAdmin()` | `ClaimAdmin(initiator : ByStr20)`|
```

2020-10-05 05:38 UTC, AmritKumar commented on contracts/ssnlist.scilla
> +  staging_admin = Some {ByStr20} initiator;
```suggestion
  staging_admin = Some {ByStr20} admin;
```

2020-10-05 05:43 UTC, AmritKumar approved these changes

2020-10-05 05:43 UTC, AmritKumar requested changes
Fix the bug.

2020-10-05 07:07 UTC, bb111189 approved these changes

2020-10-05 16:28 UTC, AmritKumar approved these changes

2020-10-05 16:57 UTC, merged