fix/remove-ssnrewardshare
Zilliqa/staking-contract pull request #218
Opened 2021-03-25 09:00 UTC by teye

## Description
This pr is a fix for a scilla bug which causes custom ADT not to be interpreted when used as a parameter. The pr replaces the `SsnRewardShare (ByStr20 Uint128)` ADT with `Pair ByStr20 Uint128`. Specifically, it replaces the existing `List SsnRewardShare` to `List (Pair ByStr20 Uint128)` for `proxy.scilla` and `ssnlist.scilla`.

## Affected Transition
`AssignStakeReward`

**Note: This pr is a series of fixes for [ZIP-19 (WIP)](https://github.com/Zilliqa/ZIP/blob/feat/zip19/zips/zip-19.md)**

2021-03-25 09:08 UTC, bb111189 commented
@jjcnn This PR is to fix the disambiguation bug for the staking contract

2021-03-29 07:05 UTC, bb111189 requested changes
changes looks fine to me except for the broken link in the comments

2021-03-29 07:05 UTC, bb111189 commented on contracts/ssnlist.scilla
> +(* https://github.com/Zilliqa/ZIP/blob/zip-11-author-fix/zips/zip-11.md#verifier *)
use the master branch
seems broken link to me

2021-03-30 02:07 UTC, bb111189 approved these changes

2021-04-01 06:58 UTC, AmritKumar approved these changes

2021-04-16 06:10 UTC, renlulu approved these changes
Looks good to me. Do notice verifier need some change corresponding to this. @teye @ansnunez

2021-04-27 09:44 UTC, merged