feat/bzil
Zilliqa/staking-contract pull request #63
Opened 2020-08-20 06:07 UTC by renlulu

** Don't merge, only for pre review purpose **

This PR introduces integration with bzils, basically there are three kind of chain calls:

1. Deposit stake => Mint bzil
2. Claim rewards => Check bzil balance
3. Claim delegate stake => Burn bzil

2020-08-24 05:42 UTC, renlulu commented on contracts/ssnlist.scilla
> +  bzil_address : ByStr20
Both proxy and bzil?

2020-08-25 10:16 UTC, anton-trunov commented on contracts/ssnlist.scilla
> +    b
```suggestion
    match a with
    | True =>
      builtin sub new old
    | False =>
      builtin sub old new
    end
```

2020-08-25 10:37 UTC, bb111189 requested changes

2020-08-25 10:37 UTC, bb111189 commented on contracts/proxy.scilla
> +transition UpgradeBzilContract(newAddress: ByStr20)
```suggestion
transition UpgradeGZILContract(newAddress: ByStr20)
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/proxy.scilla
> +      e = {_eventname : "UpgradeTo FailedNotAdmin"; gzil_address : newAddress};
```suggestion
      e = {_eventname : "UpgradeGZILContract FailedNotAdmin"; gzil_address : newAddress};
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/proxy.scilla
> +(* Transitions will be sent to bzil implemetion *)
```suggestion
(* Transitions will be sent to gZIL implemetion *)
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/ssnlist.scilla
> +  | BzilValidationFailed
```suggestion
  | GZILValidationFailed
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/ssnlist.scilla
> +      | BzilValidationFailed => Int32 -17
```suggestion
      | GZILValidationFailed => Int32 -17
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/ssnlist.scilla
> +  msg_to_bzil = {_tag : "Mint"; _recipient : addr; _amount : uint128_zero;
```suggestion
  msg_to_gzil = {_tag : "Mint"; _recipient : addr; _amount : uint128_zero; 
```

2020-08-25 10:37 UTC, bb111189 commented on contracts/ssnlist.scilla
> +  msgs = one_msg msg_to_bzil;
```suggestion
  msgs = one_msg msg_to_gzil;
```

2020-08-25 15:42 UTC, bb111189 commented on contracts/ssnlist.scilla
> +  | ExceedMaxRate
```suggestion
  | ExceedMaxCommRate
```

2020-08-25 15:42 UTC, bb111189 commented on contracts/ssnlist.scilla
> +      | ExceedMaxRate => Int32 -19
```suggestion
      | ExceedMaxCommRate => Int32 -19
```

2020-08-25 15:42 UTC, bb111189 commented on contracts/ssnlist.scilla
> +    e = ExceedMaxRate;
```suggestion
    e = ExceedMaxCommRate;
```

2020-08-25 15:43 UTC, bb111189 reviewed
Make the error code abit more verbose

2020-08-27 11:13 UTC, bb111189 approved these changes

2020-08-27 11:13 UTC, merged